export const NoteActionTypes = {
    UPDATE_TREE: 'UPDATE_TREE',
    SET_CURRENT_NODE: 'SET_CURRENT_NODE',
    UPDATE_CONTENT: 'UPDATE_CONTENT',
    ADD_NODE: 'ADD_NODE',
    DELETE_NODE: 'DELETE_NODE',
    SET_SELECTED_PROJECT: 'SET_SELECTED_PROJECT'
}